
version: '3.8'

services:
  dev :
    container_name: food-management
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - 3000:3000
#    command: npm run start:dev
    env_file:
      - ./env/.env
    networks:
      - webnet
    depends_on:
      - db
# Ten cua service chay postgres phai la db
  db :
    container_name: postgres
    image : postgres:12-alpine
    networks:
      - webnet
    env_file:
      - ./env/.dev.env
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
#      POSTGRES_DB : food-management-DB
      PG_DATA : /var/lib/postgresql/data
    ports:
      - 5433:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /var/lib/postgresql/data:/var/lib/postgresql/data
#      - db-data :/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata:
#  db-data: